name: Intermediate environment variables
on: [push, pull_request]
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }} # コンテキストの値を環境変数へセット
      PR_TITLE: ${{ github.event.pull_request.title }} # プルリクエストタイトルを環境変数へセット
    steps:
      - run: echo "${ACTOR}"
      - run: echo "${PR_TITLE}"
